#!/usr/bin/env bash

function ascii2bin()
{
  perl -lpe '$_=unpack"B*"';
}

function bin2ascii()
{
  perl -lpe '$_=pack"B*",$_';
}

function epoch2nsca()
{
  date -d @$1 "+%d/%b/%Y:%T"
}

function epoch2human()
{
  date -d @$1
}